%TEST_NODALMEMORYCAPACITY

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	m = NodalMemoryCapacity();
	 
	% get('ELCLASS')
	if isa(NodalMemoryCapacity, 'ConcreteElement')
		assert(strcmp(NodalMemoryCapacity().get('ELCLASS'), 'NodalMemoryCapacity'), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'NodalMemoryCapacity().get(''ELCLASS'') should return ''NodalMemoryCapacity''.')
	end
	 
	% getClass
	assert(strcmp(NodalMemoryCapacity.getClass(), 'NodalMemoryCapacity'), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'NodalMemoryCapacity.getClass() should return ''NodalMemoryCapacity''.')
	assert(strcmp(m.getClass(), 'NodalMemoryCapacity'), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'm.getClass() should return ''NodalMemoryCapacity''.')
	assert(strcmp(Element.getClass(m), 'NodalMemoryCapacity'), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(m) should return ''NodalMemoryCapacity''.')
	assert(strcmp(Element.getClass('NodalMemoryCapacity'), 'NodalMemoryCapacity'), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''NodalMemoryCapacity'') should return ''NodalMemoryCapacity''.')
	 
	% getSubclasses()
	assert(isequal(NodalMemoryCapacity.getSubclasses(), subclasses('NodalMemoryCapacity', [], [], true)), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'NodalMemoryCapacity.getSubclasses() should return the same result as subclasses(''NodalMemoryCapacity'', [], [], true).')
	assert(isequal(m.getSubclasses(), subclasses('NodalMemoryCapacity', [], [], true)), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''NodalMemoryCapacity'', [], [], true).')
	assert(isequal(Element.getSubclasses(m), subclasses('NodalMemoryCapacity', [], [], true)), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(m) should return the same result as subclasses(''NodalMemoryCapacity'', [], [], true).')
	assert(isequal(Element.getSubclasses('NodalMemoryCapacity'), subclasses('NodalMemoryCapacity', [], [], true)), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''NodalMemoryCapacity'') should return the same result as subclasses(''NodalMemoryCapacity'', [], [], true).')
	 
	% getProps()
	assert(isempty(NodalMemoryCapacity.getProps()) || isequal(NodalMemoryCapacity.getProps(), 1:1:length(NodalMemoryCapacity.getProps())), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'NodalMemoryCapacity.getProps() should return a row vector [1:1:N].')
	assert(isempty(NodalMemoryCapacity.getProps()) || isequal(m.getProps(), 1:1:length(NodalMemoryCapacity.getProps())), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'm.getProps() should return a row vector [1:1:N].')
	assert(isempty(NodalMemoryCapacity.getProps()) || isequal(Element.getProps(m), 1:1:length(NodalMemoryCapacity.getProps())), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(m) should return a row vector [1:1:N].')
	assert(isempty(NodalMemoryCapacity.getProps()) || isequal(Element.getProps('NodalMemoryCapacity'), 1:1:length(NodalMemoryCapacity.getProps())), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''NodalMemoryCapacity'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) NodalMemoryCapacity.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(NodalMemoryCapacity.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NodalMemoryCapacity.getProps())), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'NodalMemoryCapacity.getProps(category) does not work.')
	tmp = cellfun(@(category) m.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(NodalMemoryCapacity.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NodalMemoryCapacity.getProps())), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'm.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(m, category), categories, 'UniformOutput', false);
	assert(isempty(NodalMemoryCapacity.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NodalMemoryCapacity.getProps())), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(m, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('NodalMemoryCapacity', category), categories, 'UniformOutput', false);
	assert(isempty(NodalMemoryCapacity.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(NodalMemoryCapacity.getProps())), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''NodalMemoryCapacity'', category) does not work.')
	 
	% getPropNumber()
	assert(NodalMemoryCapacity.getPropNumber() == length(NodalMemoryCapacity.getProps()), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'NodalMemoryCapacity.getPropNumber() should return the number of properties.')
	assert(m.getPropNumber() == length(NodalMemoryCapacity.getProps()), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'm.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(m) == length(NodalMemoryCapacity.getProps()), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(m) should return the number of properties.')
	assert(Element.getPropNumber('NodalMemoryCapacity') == length(NodalMemoryCapacity.getProps()), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''NodalMemoryCapacity'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) NodalMemoryCapacity.getPropNumber(category), categories)) == NodalMemoryCapacity.getPropNumber(), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'NodalMemoryCapacity.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) m.getPropNumber(category), categories)) == NodalMemoryCapacity.getPropNumber(), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'm.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(m, category), categories)) == NodalMemoryCapacity.getPropNumber(), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(m, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('NodalMemoryCapacity', category), categories)) == NodalMemoryCapacity.getPropNumber(), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''NodalMemoryCapacity'', category) does not work.')
	 
	% existsProp(prop)
	assert(~NodalMemoryCapacity.existsProp(NaN), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'NodalMemoryCapacity.existsProp(prop) does not work.')
	assert(~m.existsProp(NaN), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'm.existsProp(prop) does not work.')
	assert(~Element.existsProp(m, NaN), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(m, prop) does not work.')
	assert(~Element.existsProp('NodalMemoryCapacity', NaN), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''NodalMemoryCapacity'', prop) does not work.')
	 
	assert_with_error('NodalMemoryCapacity.existsProp(NaN)', [BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.WRONG_INPUT], m)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.WRONG_INPUT], m)
	assert_with_error('Element.existsProp(''NodalMemoryCapacity'', NaN)', [BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:NodalMemoryCapacity.getPropNumber()
		assert(NodalMemoryCapacity.existsProp(prop), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'NodalMemoryCapacity.existsProp(prop) does not work.')
		assert(m.existsProp(prop), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.existsProp(prop) does not work.')
		assert(Element.existsProp(m, prop), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(m, prop) does not work.')
		assert(Element.existsProp('NodalMemoryCapacity', prop), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''NodalMemoryCapacity'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~NodalMemoryCapacity.existsTag(''), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'NodalMemoryCapacity.existsTag(tag) does not work.')
	assert(~m.existsTag(''), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'm.existsTag(tag) does not work.')
	assert(~Element.existsTag(m, ''), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(m, tag) does not work.')
	assert(~Element.existsTag('NodalMemoryCapacity', ''), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''NodalMemoryCapacity'', tag) does not work.')
	 
	assert_with_error('NodalMemoryCapacity.existsTag('''')', [BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.WRONG_INPUT], m)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.WRONG_INPUT], m)
	assert_with_error('Element.existsTag(''NodalMemoryCapacity'', '''')', [BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:NodalMemoryCapacity.getPropNumber()
		tag = m.getPropTag(prop);
		assert(NodalMemoryCapacity.existsTag(tag), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'NodalMemoryCapacity.existsTag(tag) does not work.')
		assert(m.existsTag(tag), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.existsTag(tag) does not work.')
		assert(Element.existsTag(m, tag), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(m, tga) does not work.')
		assert(Element.existsTag('NodalMemoryCapacity', tag), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''NodalMemoryCapacity'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:NodalMemoryCapacity.getPropNumber()
		assert(NodalMemoryCapacity.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'NodalMemoryCapacity.getPropProp(prop) does not work.')
		assert(m.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.getPropProp(prop) does not work.')
		assert(Element.getPropProp(m, prop) == prop, ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(m, prop) does not work.')
		assert(Element.getPropProp('NodalMemoryCapacity', prop) == prop, ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''NodalMemoryCapacity'', prop) does not work.')
	 
		tag = m.getPropTag(prop);
		assert(NodalMemoryCapacity.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'NodalMemoryCapacity.getPropProp(tag) does not work.')
		assert(m.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.getPropProp(tag) does not work.')
		assert(Element.getPropProp(m, tag) == prop, ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(m, tag) does not work.')
		assert(Element.getPropProp('NodalMemoryCapacity', prop) == prop, ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''NodalMemoryCapacity'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:NodalMemoryCapacity.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(strcmp(NodalMemoryCapacity.getPropTag(prop), tag), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'NodalMemoryCapacity.getPropTag(prop) does not work.')
		assert(strcmp(m.getPropTag(prop), tag), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(m, prop), tag), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(m, prop) does not work.')
		assert(strcmp(Element.getPropTag('NodalMemoryCapacity', prop), tag), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''NodalMemoryCapacity'', prop) does not work.')
	 
		assert(strcmp(NodalMemoryCapacity.getPropTag(tag), tag), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'NodalMemoryCapacity.getPropTag(tag) does not work.')
		assert(strcmp(m.getPropTag(tag), tag), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(m, tag), tag), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(m, tag) does not work.')
		assert(strcmp(Element.getPropTag('NodalMemoryCapacity', prop), tag), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''NodalMemoryCapacity'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:NodalMemoryCapacity.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(Category.existsCategory(NodalMemoryCapacity.getPropCategory(prop)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'NodalMemoryCapacity.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(m.getPropCategory(prop)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(m, prop)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(m, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(m, prop)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''NodalMemoryCapacity'', prop) does not work.')
	 
		assert(Category.existsCategory(NodalMemoryCapacity.getPropCategory(tag)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'NodalMemoryCapacity.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(m.getPropCategory(tag)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(m, tag)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(m, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(m, tag)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''NodalMemoryCapacity'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:NodalMemoryCapacity.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(Format.existsFormat(NodalMemoryCapacity.getPropFormat(prop)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'NodalMemoryCapacity.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(m.getPropFormat(prop)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(m, prop)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(m, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(m, prop)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''NodalMemoryCapacity'', prop) does not work.')
	 
		assert(Format.existsFormat(NodalMemoryCapacity.getPropFormat(tag)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'NodalMemoryCapacity.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(m.getPropFormat(tag)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(m, tag)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(m, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(m, tag)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''NodalMemoryCapacity'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:NodalMemoryCapacity.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(ischar(NodalMemoryCapacity.getPropDescription(prop)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'NodalMemoryCapacity.getPropDescription(prop) does not work.')
		assert(ischar(m.getPropDescription(prop)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(m, prop)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(m, prop) does not work.')
		assert(ischar(Element.getPropDescription(m, prop)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''NodalMemoryCapacity'', prop) does not work.')
	 
		assert(ischar(NodalMemoryCapacity.getPropDescription(tag)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'NodalMemoryCapacity.getPropDescription(tag) does not work.')
		assert(ischar(m.getPropDescription(tag)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(m, tag)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(m, tag) does not work.')
		assert(ischar(Element.getPropDescription(m, tag)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''NodalMemoryCapacity'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:NodalMemoryCapacity.getPropNumber()
		tag = m.getPropTag(prop);
	 
		settings = NodalMemoryCapacity.getPropSettings(prop);
		settings = m.getPropSettings(prop);
		settings = Element.getPropSettings(m, prop);
		settings = Element.getPropSettings('NodalMemoryCapacity', prop);
	 
		settings = NodalMemoryCapacity.getPropSettings(tag);
		settings = m.getPropSettings(tag);
		settings = Element.getPropSettings(m, tag);
		settings = Element.getPropSettings('NodalMemoryCapacity', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:NodalMemoryCapacity.getPropNumber()
		tag = m.getPropTag(prop);
	 
		default = NodalMemoryCapacity.getPropDefault(prop);
		default = m.getPropDefault(prop);
		default = Element.getPropDefault(m, prop);
		default = Element.getPropDefault('NodalMemoryCapacity', prop);
	 
		default = NodalMemoryCapacity.getPropDefault(tag);
		default = m.getPropDefault(tag);
		default = Element.getPropDefault(m, tag);
		default = Element.getPropDefault('NodalMemoryCapacity', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:NodalMemoryCapacity.getPropNumber()
		tag = m.getPropTag(prop);
	 
		conditioned_default = NodalMemoryCapacity.getPropDefaultConditioned(prop);
		conditioned_default = m.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(m, prop);
		conditioned_default = Element.getPropDefaultConditioned('NodalMemoryCapacity', prop);
	 
		conditioned_default = NodalMemoryCapacity.getPropDefaultConditioned(tag);
		conditioned_default = m.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(m, tag);
		conditioned_default = Element.getPropDefaultConditioned('NodalMemoryCapacity', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:NodalMemoryCapacity.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(~NodalMemoryCapacity.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'NodalMemoryCapacity.checkProp(prop, value) does not work.')
		assert(~m.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(m, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(m, prop, value) does not work.')
		assert(~Element.checkProp('NodalMemoryCapacity', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NodalMemoryCapacity'', prop, value) does not work.')
	 
		assert_with_error('NodalMemoryCapacity.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.WRONG_INPUT], prop, m)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.WRONG_INPUT], prop, m)
		assert_with_error('Element.checkProp(''NodalMemoryCapacity'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~NodalMemoryCapacity.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'NodalMemoryCapacity.checkProp(tag, value) does not work.')
		assert(~m.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(m, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(m, tag, value) does not work.')
		assert(~Element.checkProp('NodalMemoryCapacity', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NodalMemoryCapacity'', tag, value) does not work.')
	 
		assert_with_error('NodalMemoryCapacity.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.WRONG_INPUT], tag, m)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.WRONG_INPUT], tag, m)
		assert_with_error('Element.checkProp(''NodalMemoryCapacity'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(NodalMemoryCapacity.checkProp(prop, Element.getPropDefaultConditioned(NodalMemoryCapacity, prop)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'NodalMemoryCapacity.checkProp(prop, <conditioned default value>) does not work.')
		assert(m.checkProp(prop, Element.getPropDefaultConditioned(NodalMemoryCapacity, prop)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(m, prop, Element.getPropDefaultConditioned(NodalMemoryCapacity, prop)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(m, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('NodalMemoryCapacity', prop, Element.getPropDefaultConditioned(NodalMemoryCapacity, prop)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NodalMemoryCapacity'', prop, <conditioned default value>) does not work.')
	 
		assert(NodalMemoryCapacity.checkProp(tag, Element.getPropDefaultConditioned(NodalMemoryCapacity, prop)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'NodalMemoryCapacity.checkProp(tag, <conditioned default value>) does not work.')
		assert(m.checkProp(tag, Element.getPropDefaultConditioned(NodalMemoryCapacity, prop)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(m, tag, Element.getPropDefaultConditioned(NodalMemoryCapacity, prop)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(m, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('NodalMemoryCapacity', tag, Element.getPropDefaultConditioned(NodalMemoryCapacity, prop)), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''NodalMemoryCapacity'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = NodalMemoryCapacity( ...
		NodalMemoryCapacity.ELCLASS, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.NAME, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.DESCRIPTION, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.TEMPLATE, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.TEMPLATE), ...
		NodalMemoryCapacity.ID, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.ID), ...
		NodalMemoryCapacity.LABEL, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.LABEL), ...
		NodalMemoryCapacity.NOTES, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.NOTES), ...
		NodalMemoryCapacity.TOSTRING, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.SHAPE, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.SCOPE, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.PARAMETRICITY, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.COMPATIBLE_GRAPHS, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.G, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.G), ...
		NodalMemoryCapacity.M, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.PFM, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.PFM), ...
		NodalMemoryCapacity.TRIALS, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.TRIALS), ...
		NodalMemoryCapacity.TRAINING_SAMPLES, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.TRAINING_SAMPLES), ...
		NodalMemoryCapacity.TAU_MAX, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.TAU_MAX), ...
		NodalMemoryCapacity.N_LOWER, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.N_LOWER), ...
		NodalMemoryCapacity.DENSITY, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.DENSITY) ...
		);
	 
	for prop = 1:1:NodalMemoryCapacity.getPropNumber()
	 
		% excluded props
		if any(prop == [NodalMemoryCapacity.PFM])
			continue
		end
	 
		TAG = upper(NodalMemoryCapacity.getPropTag(prop));
		switch NodalMemoryCapacity.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					m.getr(prop) == NodalMemoryCapacity.getNoValue(), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['Being a ' NodalMemoryCapacity.getCategoryName(NodalMemoryCapacity.getPropCategory(prop)) ', NodalMemoryCapacity.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NodalMemoryCapacity.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					m.getr(TAG) == NodalMemoryCapacity.getNoValue(), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['Being a ' NodalMemoryCapacity.getCategoryName(NodalMemoryCapacity.getPropCategory(prop)) ', NodalMemoryCapacity.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NodalMemoryCapacity.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(m.getPropSettings(prop))
					assert( ...
						m.checkFormat(m.getPropFormat(prop), m.get(prop)), ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						['NodalMemoryCapacity.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						m.checkFormat(m.getPropFormat(prop), m.get(prop), m.getPropSettings(prop)), ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						['NodalMemoryCapacity.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					m.getr(prop) == NodalMemoryCapacity.getNoValue(), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['Being a ' NodalMemoryCapacity.getCategoryName(NodalMemoryCapacity.getPropCategory(prop)) ', NodalMemoryCapacity.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NodalMemoryCapacity.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					m.getr(TAG) == NodalMemoryCapacity.getNoValue(), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['Being a ' NodalMemoryCapacity.getCategoryName(NodalMemoryCapacity.getPropCategory(prop)) ', NodalMemoryCapacity.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in NodalMemoryCapacity.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':NodalMemoryCapacity']);
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(m.getPropSettings(prop))
					assert( ...
						m.checkFormat(m.getPropFormat(prop), m.get(prop)), ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						['NodalMemoryCapacity.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						m.checkFormat(m.getPropFormat(prop), m.get(prop), m.getPropSettings(prop)), ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						['NodalMemoryCapacity.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(m.getr(prop), NodalMemoryCapacity.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by NodalMemoryCapacity.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in NodalMemoryCapacity.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(m.getr(TAG), NodalMemoryCapacity.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.getr(' TAG ') must be inizialized to its default value ' ...
					'given by NodalMemoryCapacity.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in NodalMemoryCapacity.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = NodalMemoryCapacity( ...
		NodalMemoryCapacity.ELCLASS, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.NAME, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.DESCRIPTION, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.TEMPLATE, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.TEMPLATE), ...
		NodalMemoryCapacity.ID, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.ID), ...
		NodalMemoryCapacity.LABEL, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.LABEL), ...
		NodalMemoryCapacity.NOTES, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.NOTES), ...
		NodalMemoryCapacity.TOSTRING, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.SHAPE, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.SCOPE, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.PARAMETRICITY, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.COMPATIBLE_GRAPHS, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.G, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.G), ...
		NodalMemoryCapacity.M, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.PFM, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.PFM), ...
		NodalMemoryCapacity.TRIALS, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.TRIALS), ...
		NodalMemoryCapacity.TRAINING_SAMPLES, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.TRAINING_SAMPLES), ...
		NodalMemoryCapacity.TAU_MAX, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.TAU_MAX), ...
		NodalMemoryCapacity.N_LOWER, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.N_LOWER), ...
		NodalMemoryCapacity.DENSITY, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.DENSITY) ...
		);
	 
	for prop = 1:1:NodalMemoryCapacity.getPropNumber()
	 
		% excluded props
		if any(prop == [NodalMemoryCapacity.PFM])
			continue
		end
	 
		TAG = upper(NodalMemoryCapacity.getPropTag(prop));
		switch NodalMemoryCapacity.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(m.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					m.checkFormat(m.getPropFormat(prop), m.getr(prop),m.getPropSettings(prop)), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':NodalMemoryCapacity']);
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':NodalMemoryCapacity']);
	% 			assert( ...
	% 				~isa(m.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
	% 				['NodalMemoryCapacity.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(m.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
	% 				['NodalMemoryCapacity.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				m.checkFormat(m.getPropFormat(prop), m.getr(prop),m.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
	% 				['NodalMemoryCapacity.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':NodalMemoryCapacity']);
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(m.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					m.checkFormat(m.getPropFormat(prop), m.getr(prop),m.getPropSettings(prop)), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if m.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:NodalMemoryCapacity');
					delete(ancestor(m.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(NodalMemoryCapacity.getProps(Category.RESULT))
		for prop = 1:1:NodalMemoryCapacity.getPropNumber()
	 
			% excluded props
			if any(prop == [NodalMemoryCapacity.PFM])
				continue
			end
	 
			switch NodalMemoryCapacity.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						m.isLocked(prop), ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						['NodalMemoryCapacity.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~m.isLocked(prop), ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						['NodalMemoryCapacity.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = NodalMemoryCapacity();
	 
	for prop = 1:1:NodalMemoryCapacity.getPropNumber()
		TAG = upper(NodalMemoryCapacity.getPropTag(prop));
		assert( ...
			~m.isLocked(prop), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			['NodalMemoryCapacity.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~m.isLocked(TAG), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			['NodalMemoryCapacity.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	m.lock()
	 
	for prop = 1:1:NodalMemoryCapacity.getPropNumber()
		switch NodalMemoryCapacity.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					m.isLocked(prop), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~m.isLocked(prop), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = NodalMemoryCapacity();
	 
	warning_backup = warning('off', 'BRAPH2:NodalMemoryCapacity');
	for prop = 1:1:NodalMemoryCapacity.getPropNumber()
		m.lock(prop)
		switch NodalMemoryCapacity.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					m.isLocked(prop), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~m.isLocked(prop), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = NodalMemoryCapacity();
	 
	for prop = 1:1:NodalMemoryCapacity.getPropNumber()
		TAG = upper(NodalMemoryCapacity.getPropTag(prop));
		assert( ...
			m.isChecked(prop), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			['NodalMemoryCapacity.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			m.isChecked(TAG), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			['NodalMemoryCapacity.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	m.unchecked()
	 
	for prop = 1:1:NodalMemoryCapacity.getPropNumber()
		assert( ...
			~m.isChecked(prop), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			['NodalMemoryCapacity.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	m.checked()
	 
	for prop = 1:1:NodalMemoryCapacity.getPropNumber()
		assert( ...
			m.isChecked(prop), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			['NodalMemoryCapacity.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic NodalMemoryCapacity
	m_0 = NodalMemoryCapacity( ...
		NodalMemoryCapacity.ELCLASS, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.NAME, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.DESCRIPTION, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.TEMPLATE, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.TEMPLATE), ...
		NodalMemoryCapacity.ID, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.ID), ...
		NodalMemoryCapacity.LABEL, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.LABEL), ...
		NodalMemoryCapacity.NOTES, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.NOTES), ...
		NodalMemoryCapacity.TOSTRING, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.SHAPE, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.SCOPE, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.PARAMETRICITY, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.COMPATIBLE_GRAPHS, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.G, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.G), ...
		NodalMemoryCapacity.M, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.PFM, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.PFM), ...
		NodalMemoryCapacity.TRIALS, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.TRIALS), ...
		NodalMemoryCapacity.TRAINING_SAMPLES, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.TRAINING_SAMPLES), ...
		NodalMemoryCapacity.TAU_MAX, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.TAU_MAX), ...
		NodalMemoryCapacity.N_LOWER, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.N_LOWER), ...
		NodalMemoryCapacity.DENSITY, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.DENSITY) ...
		);
	 
	% NodalMemoryCapacity with 1st callbacks
	m_1 = NodalMemoryCapacity( ...
		NodalMemoryCapacity.ELCLASS, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.NAME, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.DESCRIPTION, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.TEMPLATE, m_0.getCallback(4), ..., ...
		NodalMemoryCapacity.ID, m_0.getCallback(5), ..., ...
		NodalMemoryCapacity.LABEL, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.LABEL), ...
		NodalMemoryCapacity.NOTES, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.NOTES), ...
		NodalMemoryCapacity.TOSTRING, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.SHAPE, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.SCOPE, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.PARAMETRICITY, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.COMPATIBLE_GRAPHS, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.G, m_0.getCallback(13), ..., ...
		NodalMemoryCapacity.M, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.PFM, m_0.getCallback(15), ..., ...
		NodalMemoryCapacity.TRIALS, m_0.getCallback(16), ..., ...
		NodalMemoryCapacity.TRAINING_SAMPLES, m_0.getCallback(17), ..., ...
		NodalMemoryCapacity.TAU_MAX, m_0.getCallback(18), ..., ...
		NodalMemoryCapacity.N_LOWER, m_0.getCallback(19), ..., ...
		NodalMemoryCapacity.DENSITY, m_0.getCallback(20) ... ...
		);
	 
	prop_number = NodalMemoryCapacity.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NodalMemoryCapacity.getPropTag(prop));
		switch NodalMemoryCapacity.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(m_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(m_1.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(m_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% NodalMemoryCapacity with 2nd callbacks
	m_2 = NodalMemoryCapacity( ...
		NodalMemoryCapacity.ELCLASS, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.NAME, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.DESCRIPTION, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.TEMPLATE, m_1.getCallback(4), ..., ...
		NodalMemoryCapacity.ID, m_1.getCallback(5), ..., ...
		NodalMemoryCapacity.LABEL, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.LABEL), ...
		NodalMemoryCapacity.NOTES, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.NOTES), ...
		NodalMemoryCapacity.TOSTRING, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.SHAPE, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.SCOPE, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.PARAMETRICITY, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.COMPATIBLE_GRAPHS, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.G, m_1.getCallback(13), ..., ...
		NodalMemoryCapacity.M, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.PFM, m_1.getCallback(15), ..., ...
		NodalMemoryCapacity.TRIALS, m_1.getCallback(16), ..., ...
		NodalMemoryCapacity.TRAINING_SAMPLES, m_1.getCallback(17), ..., ...
		NodalMemoryCapacity.TAU_MAX, m_1.getCallback(18), ..., ...
		NodalMemoryCapacity.N_LOWER, m_1.getCallback(19), ..., ...
		NodalMemoryCapacity.DENSITY, m_1.getCallback(20) ... ...
		);
	 
	prop_number = NodalMemoryCapacity.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NodalMemoryCapacity.getPropTag(prop));
		switch NodalMemoryCapacity.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(m_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(m_2.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(m_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% NodalMemoryCapacity with 3rd callbacks
	m_3 = NodalMemoryCapacity( ...
		NodalMemoryCapacity.ELCLASS, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.NAME, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.DESCRIPTION, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.TEMPLATE, m_2.getCallback(4), ..., ...
		NodalMemoryCapacity.ID, m_2.getCallback(5), ..., ...
		NodalMemoryCapacity.LABEL, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.LABEL), ...
		NodalMemoryCapacity.NOTES, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.NOTES), ...
		NodalMemoryCapacity.TOSTRING, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.SHAPE, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.SCOPE, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.PARAMETRICITY, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.COMPATIBLE_GRAPHS, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.G, m_2.getCallback(13), ..., ...
		NodalMemoryCapacity.M, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.PFM, m_2.getCallback(15), ..., ...
		NodalMemoryCapacity.TRIALS, m_2.getCallback(16), ..., ...
		NodalMemoryCapacity.TRAINING_SAMPLES, m_2.getCallback(17), ..., ...
		NodalMemoryCapacity.TAU_MAX, m_2.getCallback(18), ..., ...
		NodalMemoryCapacity.N_LOWER, m_2.getCallback(19), ..., ...
		NodalMemoryCapacity.DENSITY, m_2.getCallback(20) ... ...
		);
	 
	prop_number = NodalMemoryCapacity.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(NodalMemoryCapacity.getPropTag(prop));
		switch NodalMemoryCapacity.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(m_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(m_3.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(m_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	m = NodalMemoryCapacity();
	 
	m_copy = m.copy();
	 
	assert(m_copy ~= m, ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'NodalMemoryCapacity.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(m_copy, m), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'NodalMemoryCapacity.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:NodalMemoryCapacity.getPropNumber()
		value = m.getr(prop);
		value_copy = m_copy.getr(prop);
		switch NodalMemoryCapacity.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					'NodalMemoryCapacity.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'NodalMemoryCapacity.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'NodalMemoryCapacity.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'NodalMemoryCapacity.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
							'NodalMemoryCapacity.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
							'NodalMemoryCapacity.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'NodalMemoryCapacity.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					m_copy.isLocked(prop) == m.isLocked(prop), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					'NodalMemoryCapacity.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					m_copy.isChecked(prop) == m.isChecked(prop), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					'NodalMemoryCapacity.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					m_copy.getPropSeed(prop) == m.getPropSeed(prop), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					'NodalMemoryCapacity.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	m = NodalMemoryCapacity( ...
		NodalMemoryCapacity.ELCLASS, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.NAME, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.DESCRIPTION, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.TEMPLATE, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.TEMPLATE), ...
		NodalMemoryCapacity.ID, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.ID), ...
		NodalMemoryCapacity.LABEL, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.LABEL), ...
		NodalMemoryCapacity.NOTES, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.NOTES), ...
		NodalMemoryCapacity.TOSTRING, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.SHAPE, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.SCOPE, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.PARAMETRICITY, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.COMPATIBLE_GRAPHS, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.G, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.G), ...
		NodalMemoryCapacity.M, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.PFM, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.PFM), ...
		NodalMemoryCapacity.TRIALS, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.TRIALS), ...
		NodalMemoryCapacity.TRAINING_SAMPLES, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.TRAINING_SAMPLES), ...
		NodalMemoryCapacity.TAU_MAX, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.TAU_MAX), ...
		NodalMemoryCapacity.N_LOWER, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.N_LOWER), ...
		NodalMemoryCapacity.DENSITY, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.DENSITY) ...
		);
	 
	for prop = 1:1:NodalMemoryCapacity.getPropNumber()
		if NodalMemoryCapacity.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':NodalMemoryCapacity']);
			% m.memorize(prop);
			% warning(warning_backup)
		elseif NodalMemoryCapacity.getPropCategory(prop) == Category.EVANESCENT && m.getPropFormat(prop) == Format.HANDLE
			m.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:NodalMemoryCapacity');
			delete(ancestor(m.get(prop), 'figure'))
			warning(warning_backup)
		else
			m.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	m_copy = m.copy();
	 
	for prop = 1:1:NodalMemoryCapacity.getPropNumber()
		value = m.getr(prop);
		value_copy = m_copy.getr(prop);
		switch NodalMemoryCapacity.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					'NodalMemoryCapacity.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'NodalMemoryCapacity.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'NodalMemoryCapacity.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'NodalMemoryCapacity.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
							'NodalMemoryCapacity.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
							'NodalMemoryCapacity.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'NodalMemoryCapacity.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						m_copy.isLocked(prop) == m.isLocked(prop), ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'NodalMemoryCapacity.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						m_copy.isChecked(prop) == m.isChecked(prop), ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'NodalMemoryCapacity.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						m_copy.getPropSeed(prop) == m.getPropSeed(prop), ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'NodalMemoryCapacity.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	m_0 = NodalMemoryCapacity( ...
		NodalMemoryCapacity.ELCLASS, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.NAME, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.DESCRIPTION, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.TEMPLATE, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.TEMPLATE), ...
		NodalMemoryCapacity.ID, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.ID), ...
		NodalMemoryCapacity.LABEL, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.LABEL), ...
		NodalMemoryCapacity.NOTES, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.NOTES), ...
		NodalMemoryCapacity.TOSTRING, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.SHAPE, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.SCOPE, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.PARAMETRICITY, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.COMPATIBLE_GRAPHS, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.G, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.G), ...
		NodalMemoryCapacity.M, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.PFM, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.PFM), ...
		NodalMemoryCapacity.TRIALS, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.TRIALS), ...
		NodalMemoryCapacity.TRAINING_SAMPLES, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.TRAINING_SAMPLES), ...
		NodalMemoryCapacity.TAU_MAX, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.TAU_MAX), ...
		NodalMemoryCapacity.N_LOWER, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.N_LOWER), ...
		NodalMemoryCapacity.DENSITY, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.DENSITY) ...
		);
	 
	m = NodalMemoryCapacity( ...
		NodalMemoryCapacity.ELCLASS, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.NAME, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.DESCRIPTION, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.TEMPLATE, m_0.getCallback(4), ..., ...
		NodalMemoryCapacity.ID, m_0.getCallback(5), ..., ...
		NodalMemoryCapacity.LABEL, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.LABEL), ...
		NodalMemoryCapacity.NOTES, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.NOTES), ...
		NodalMemoryCapacity.TOSTRING, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.SHAPE, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.SCOPE, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.PARAMETRICITY, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.COMPATIBLE_GRAPHS, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.G, m_0.getCallback(13), ..., ...
		NodalMemoryCapacity.M, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.PFM, m_0.getCallback(15), ..., ...
		NodalMemoryCapacity.TRIALS, m_0.getCallback(16), ..., ...
		NodalMemoryCapacity.TRAINING_SAMPLES, m_0.getCallback(17), ..., ...
		NodalMemoryCapacity.TAU_MAX, m_0.getCallback(18), ..., ...
		NodalMemoryCapacity.N_LOWER, m_0.getCallback(19), ..., ...
		NodalMemoryCapacity.DENSITY, m_0.getCallback(20) ... ...
		);
	 
	m_copy = m.copy();
	m_0_copy = m_copy.getr('ID').get('EL');
	 
	for prop = 1:1:NodalMemoryCapacity.getPropNumber()
		value = m.getr(prop);
		value_copy = m_copy.getr(prop);
		switch NodalMemoryCapacity.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					'NodalMemoryCapacity.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'NodalMemoryCapacity.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'NodalMemoryCapacity.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'NodalMemoryCapacity.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
							'NodalMemoryCapacity.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
							'NodalMemoryCapacity.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'NodalMemoryCapacity.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == m_0.getCallback(prop), ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'NodalMemoryCapacity.copy() does not work. The callback should be obtained from NodalMemoryCapacity.getCallback().' ...
						)
					assert( ...
						value_copy == m_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'NodalMemoryCapacity.copy() does not work. The callback should be obtained from NodalMemoryCapacity.getCallback().' ...
						)
				end
	 
					assert( ...
						m_copy.isLocked(prop) == m.isLocked(prop), ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'NodalMemoryCapacity.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						m_copy.isChecked(prop) == m.isChecked(prop), ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'NodalMemoryCapacity.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						m_copy.getPropSeed(prop) == m.getPropSeed(prop), ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'NodalMemoryCapacity.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m_template = NodalMemoryCapacity();
	m = NodalMemoryCapacity('TEMPLATE', m_template);
	 
	for prop = 1:1:NodalMemoryCapacity.getPropNumber()
	 
		% excluded props
		if any(prop == [NodalMemoryCapacity.PFM])
			continue
		end
	 
		TAG = upper(NodalMemoryCapacity.getPropTag(prop));
		switch NodalMemoryCapacity.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == NodalMemoryCapacity.TEMPLATE
					assert( ...
						isa(m.getr(prop), 'NodalMemoryCapacity'), ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'NodalMemoryCapacity TEMPLATE does not work. NodalMemoryCapacity.getr(''TEMPLATE'') should be a NodalMemoryCapacity element.' ...
						)
					assert( ...
						isa(m_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'NodalMemoryCapacity TEMPLATE does not work. NodalMemoryCapacity_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(m.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						['NodalMemoryCapacity TEMPLATE does not work. NodalMemoryCapacity.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						m.getr(prop).get('EL') == m_template && m.getr(prop).get('PROP') == prop && strcmp(m.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						['NodalMemoryCapacity TEMPLATE does not work. NodalMemoryCapacity.getr(' TAG ') should be a Callback to m_template.' TAG '.'] ...
						)
					assert( ...
						isa(m_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						['NodalMemoryCapacity TEMPLATE does not work. NodalMemoryCapacity_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity TEMPLATE does not work. NodalMemoryCapacity.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(m_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['NodalMemoryCapacity TEMPLATE does not work. NodalMemoryCapacity_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = NodalMemoryCapacity( ...
		NodalMemoryCapacity.ELCLASS, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.NAME, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.DESCRIPTION, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.TEMPLATE, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.TEMPLATE), ...
		NodalMemoryCapacity.ID, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.ID), ...
		NodalMemoryCapacity.LABEL, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.LABEL), ...
		NodalMemoryCapacity.NOTES, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.NOTES), ...
		NodalMemoryCapacity.TOSTRING, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.SHAPE, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.SCOPE, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.PARAMETRICITY, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.COMPATIBLE_GRAPHS, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.G, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.G), ...
		NodalMemoryCapacity.M, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.PFM, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.PFM), ...
		NodalMemoryCapacity.TRIALS, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.TRIALS), ...
		NodalMemoryCapacity.TRAINING_SAMPLES, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.TRAINING_SAMPLES), ...
		NodalMemoryCapacity.TAU_MAX, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.TAU_MAX), ...
		NodalMemoryCapacity.N_LOWER, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.N_LOWER), ...
		NodalMemoryCapacity.DENSITY, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.DENSITY) ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'nodalmemorycapacity_to_be_erased.b2'];
	 
	Element.save(m, filename)
	 
	m_loaded = Element.load(filename);
	 
	assert( ...
		isequal(m.copy(), m_loaded), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'NodalMemoryCapacity.save(m) and/or NodalMemoryCapacity.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = NodalMemoryCapacity( ...
		NodalMemoryCapacity.ELCLASS, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.NAME, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.DESCRIPTION, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.TEMPLATE, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.TEMPLATE), ...
		NodalMemoryCapacity.ID, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.ID), ...
		NodalMemoryCapacity.LABEL, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.LABEL), ...
		NodalMemoryCapacity.NOTES, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.NOTES), ...
		NodalMemoryCapacity.TOSTRING, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.SHAPE, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.SCOPE, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.PARAMETRICITY, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.COMPATIBLE_GRAPHS, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.G, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.G), ...
		NodalMemoryCapacity.M, NodalMemoryCapacity.getNoValue(), ...
		NodalMemoryCapacity.PFM, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.PFM), ...
		NodalMemoryCapacity.TRIALS, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.TRIALS), ...
		NodalMemoryCapacity.TRAINING_SAMPLES, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.TRAINING_SAMPLES), ...
		NodalMemoryCapacity.TAU_MAX, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.TAU_MAX), ...
		NodalMemoryCapacity.N_LOWER, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.N_LOWER), ...
		NodalMemoryCapacity.DENSITY, NodalMemoryCapacity.getPropDefault(NodalMemoryCapacity.DENSITY) ...
		);
	 
	[json, struct, el_list] = encodeJSON(m);
	[m_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(m_dec ~= m, ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'NodalMemoryCapacity.encodeJSON() or NodalMemoryCapacity.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) NodalMemoryCapacity.getPropFormat(prop), num2cell(NodalMemoryCapacity.getProps())) == Format.HANDLE) && all(cellfun(@(prop) NodalMemoryCapacity.getPropFormat(prop), num2cell(NodalMemoryCapacity.getProps())) == Format.NET)
		assert(isequal(m_dec, m), ...
			[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'NodalMemoryCapacity.encodeJSON() or NodalMemoryCapacity.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: example test
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	test_MC('nodal')
end

%% Test 13: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':NodalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		[' When testing NodalMemoryCapacity no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 14: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

