%TEST_GLOBALMEMORYCAPACITY

%% Test 1: Inspection Methods
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	categories = num2cell(Category.getCategories());
	m = GlobalMemoryCapacity();
	 
	% get('ELCLASS')
	if isa(GlobalMemoryCapacity, 'ConcreteElement')
		assert(strcmp(GlobalMemoryCapacity().get('ELCLASS'), 'GlobalMemoryCapacity'), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'GlobalMemoryCapacity().get(''ELCLASS'') should return ''GlobalMemoryCapacity''.')
	end
	 
	% getClass
	assert(strcmp(GlobalMemoryCapacity.getClass(), 'GlobalMemoryCapacity'), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'GlobalMemoryCapacity.getClass() should return ''GlobalMemoryCapacity''.')
	assert(strcmp(m.getClass(), 'GlobalMemoryCapacity'), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'm.getClass() should return ''GlobalMemoryCapacity''.')
	assert(strcmp(Element.getClass(m), 'GlobalMemoryCapacity'), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(m) should return ''GlobalMemoryCapacity''.')
	assert(strcmp(Element.getClass('GlobalMemoryCapacity'), 'GlobalMemoryCapacity'), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.getClass(''GlobalMemoryCapacity'') should return ''GlobalMemoryCapacity''.')
	 
	% getSubclasses()
	assert(isequal(GlobalMemoryCapacity.getSubclasses(), subclasses('GlobalMemoryCapacity', [], [], true)), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'GlobalMemoryCapacity.getSubclasses() should return the same result as subclasses(''GlobalMemoryCapacity'', [], [], true).')
	assert(isequal(m.getSubclasses(), subclasses('GlobalMemoryCapacity', [], [], true)), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'el.getSubclasses() should return the same result as subclasses(''GlobalMemoryCapacity'', [], [], true).')
	assert(isequal(Element.getSubclasses(m), subclasses('GlobalMemoryCapacity', [], [], true)), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(m) should return the same result as subclasses(''GlobalMemoryCapacity'', [], [], true).')
	assert(isequal(Element.getSubclasses('GlobalMemoryCapacity'), subclasses('GlobalMemoryCapacity', [], [], true)), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.getSubclasses(''GlobalMemoryCapacity'') should return the same result as subclasses(''GlobalMemoryCapacity'', [], [], true).')
	 
	% getProps()
	assert(isempty(GlobalMemoryCapacity.getProps()) || isequal(GlobalMemoryCapacity.getProps(), 1:1:length(GlobalMemoryCapacity.getProps())), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'GlobalMemoryCapacity.getProps() should return a row vector [1:1:N].')
	assert(isempty(GlobalMemoryCapacity.getProps()) || isequal(m.getProps(), 1:1:length(GlobalMemoryCapacity.getProps())), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'm.getProps() should return a row vector [1:1:N].')
	assert(isempty(GlobalMemoryCapacity.getProps()) || isequal(Element.getProps(m), 1:1:length(GlobalMemoryCapacity.getProps())), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(m) should return a row vector [1:1:N].')
	assert(isempty(GlobalMemoryCapacity.getProps()) || isequal(Element.getProps('GlobalMemoryCapacity'), 1:1:length(GlobalMemoryCapacity.getProps())), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''GlobalMemoryCapacity'') should return a row vector [1:1:N].')
	 
	% getProps(category)
	tmp = cellfun(@(category) GlobalMemoryCapacity.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(GlobalMemoryCapacity.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(GlobalMemoryCapacity.getProps())), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'GlobalMemoryCapacity.getProps(category) does not work.')
	tmp = cellfun(@(category) m.getProps(category), categories, 'UniformOutput', false);
	assert(isempty(GlobalMemoryCapacity.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(GlobalMemoryCapacity.getProps())), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'm.getProps(category) does not work.')
	tmp = cellfun(@(category) Element.getProps(m, category), categories, 'UniformOutput', false);
	assert(isempty(GlobalMemoryCapacity.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(GlobalMemoryCapacity.getProps())), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(m, category) does not work.')
	tmp = cellfun(@(category) Element.getProps('GlobalMemoryCapacity', category), categories, 'UniformOutput', false);
	assert(isempty(GlobalMemoryCapacity.getProps()) || isequal(sort(horzcat(tmp{:})), 1:1:length(GlobalMemoryCapacity.getProps())), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.getProps(''GlobalMemoryCapacity'', category) does not work.')
	 
	% getPropNumber()
	assert(GlobalMemoryCapacity.getPropNumber() == length(GlobalMemoryCapacity.getProps()), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'GlobalMemoryCapacity.getPropNumber() should return the number of properties.')
	assert(m.getPropNumber() == length(GlobalMemoryCapacity.getProps()), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'm.getPropNumber() should return the number of properties.')
	assert(Element.getPropNumber(m) == length(GlobalMemoryCapacity.getProps()), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(m) should return the number of properties.')
	assert(Element.getPropNumber('GlobalMemoryCapacity') == length(GlobalMemoryCapacity.getProps()), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''GlobalMemoryCapacity'') should return the number of properties.')
	 
	% getPropNumber(category)
	assert(sum(cellfun(@(category) GlobalMemoryCapacity.getPropNumber(category), categories)) == GlobalMemoryCapacity.getPropNumber(), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'GlobalMemoryCapacity.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) m.getPropNumber(category), categories)) == GlobalMemoryCapacity.getPropNumber(), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'm.getPropNumber(category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber(m, category), categories)) == GlobalMemoryCapacity.getPropNumber(), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(m, category) does not work.')
	assert(sum(cellfun(@(category) Element.getPropNumber('GlobalMemoryCapacity', category), categories)) == GlobalMemoryCapacity.getPropNumber(), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.getPropNumber(''GlobalMemoryCapacity'', category) does not work.')
	 
	% existsProp(prop)
	assert(~GlobalMemoryCapacity.existsProp(NaN), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'GlobalMemoryCapacity.existsProp(prop) does not work.')
	assert(~m.existsProp(NaN), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'm.existsProp(prop) does not work.')
	assert(~Element.existsProp(m, NaN), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(m, prop) does not work.')
	assert(~Element.existsProp('GlobalMemoryCapacity', NaN), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.existsProp(''GlobalMemoryCapacity'', prop) does not work.')
	 
	assert_with_error('GlobalMemoryCapacity.existsProp(NaN)', [BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsProp(NaN)', [BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.WRONG_INPUT], m)
	assert_with_error('Element.existsProp(varargin{1}, NaN)', [BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.WRONG_INPUT], m)
	assert_with_error('Element.existsProp(''GlobalMemoryCapacity'', NaN)', [BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:GlobalMemoryCapacity.getPropNumber()
		assert(GlobalMemoryCapacity.existsProp(prop), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'GlobalMemoryCapacity.existsProp(prop) does not work.')
		assert(m.existsProp(prop), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.existsProp(prop) does not work.')
		assert(Element.existsProp(m, prop), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(m, prop) does not work.')
		assert(Element.existsProp('GlobalMemoryCapacity', prop), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.existsProp(''GlobalMemoryCapacity'', prop) does not work.')
	end
	 
	% existsTag(tag)
	assert(~GlobalMemoryCapacity.existsTag(''), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'GlobalMemoryCapacity.existsTag(tag) does not work.')
	assert(~m.existsTag(''), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'm.existsTag(tag) does not work.')
	assert(~Element.existsTag(m, ''), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(m, tag) does not work.')
	assert(~Element.existsTag('GlobalMemoryCapacity', ''), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'Element.existsTag(''GlobalMemoryCapacity'', tag) does not work.')
	 
	assert_with_error('GlobalMemoryCapacity.existsTag('''')', [BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.WRONG_INPUT])
	assert_with_error('varargin{1}.existsTag('''')', [BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.WRONG_INPUT], m)
	assert_with_error('Element.existsTag(varargin{1}, '''')', [BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.WRONG_INPUT], m)
	assert_with_error('Element.existsTag(''GlobalMemoryCapacity'', '''')', [BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.WRONG_INPUT])
	 
	for prop = 1:1:GlobalMemoryCapacity.getPropNumber()
		tag = m.getPropTag(prop);
		assert(GlobalMemoryCapacity.existsTag(tag), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'GlobalMemoryCapacity.existsTag(tag) does not work.')
		assert(m.existsTag(tag), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.existsTag(tag) does not work.')
		assert(Element.existsTag(m, tag), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(m, tga) does not work.')
		assert(Element.existsTag('GlobalMemoryCapacity', tag), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.existsTag(''GlobalMemoryCapacity'', tag) does not work.')
	end
	 
	% getPropProp(pointer)
	for prop = 1:1:GlobalMemoryCapacity.getPropNumber()
		assert(GlobalMemoryCapacity.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'GlobalMemoryCapacity.getPropProp(prop) does not work.')
		assert(m.getPropProp(prop) == prop, ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.getPropProp(prop) does not work.')
		assert(Element.getPropProp(m, prop) == prop, ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(m, prop) does not work.')
		assert(Element.getPropProp('GlobalMemoryCapacity', prop) == prop, ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''GlobalMemoryCapacity'', prop) does not work.')
	 
		tag = m.getPropTag(prop);
		assert(GlobalMemoryCapacity.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'GlobalMemoryCapacity.getPropProp(tag) does not work.')
		assert(m.getPropProp(tag) == prop, ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.getPropProp(tag) does not work.')
		assert(Element.getPropProp(m, tag) == prop, ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(m, tag) does not work.')
		assert(Element.getPropProp('GlobalMemoryCapacity', prop) == prop, ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropProp(''GlobalMemoryCapacity'', tag) does not work.')
	end
	 
	% getPropTag(pointer)
	for prop = 1:1:GlobalMemoryCapacity.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(strcmp(GlobalMemoryCapacity.getPropTag(prop), tag), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'GlobalMemoryCapacity.getPropTag(prop) does not work.')
		assert(strcmp(m.getPropTag(prop), tag), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.getPropTag(prop) does not work.')
		assert(strcmp(Element.getPropTag(m, prop), tag), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(m, prop) does not work.')
		assert(strcmp(Element.getPropTag('GlobalMemoryCapacity', prop), tag), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''GlobalMemoryCapacity'', prop) does not work.')
	 
		assert(strcmp(GlobalMemoryCapacity.getPropTag(tag), tag), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'GlobalMemoryCapacity.getPropTag(tag) does not work.')
		assert(strcmp(m.getPropTag(tag), tag), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.getPropTag(tag) does not work.')
		assert(strcmp(Element.getPropTag(m, tag), tag), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(m, tag) does not work.')
		assert(strcmp(Element.getPropTag('GlobalMemoryCapacity', prop), tag), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropTag(''GlobalMemoryCapacity'', tag) does not work.')
	end
	 
	% getPropCategory(pointer)
	for prop = 1:1:GlobalMemoryCapacity.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(Category.existsCategory(GlobalMemoryCapacity.getPropCategory(prop)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'GlobalMemoryCapacity.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(m.getPropCategory(prop)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.getPropCategory(prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(m, prop)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(m, prop) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(m, prop)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''GlobalMemoryCapacity'', prop) does not work.')
	 
		assert(Category.existsCategory(GlobalMemoryCapacity.getPropCategory(tag)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'GlobalMemoryCapacity.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(m.getPropCategory(tag)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.getPropCategory(tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(m, tag)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(m, tag) does not work.')
		assert(Category.existsCategory(Element.getPropCategory(m, tag)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropCategory(''GlobalMemoryCapacity'', tag) does not work.')
	end
	 
	% getPropFormat(pointer)
	for prop = 1:1:GlobalMemoryCapacity.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(Format.existsFormat(GlobalMemoryCapacity.getPropFormat(prop)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'GlobalMemoryCapacity.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(m.getPropFormat(prop)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.getPropFormat(prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(m, prop)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(m, prop) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(m, prop)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''GlobalMemoryCapacity'', prop) does not work.')
	 
		assert(Format.existsFormat(GlobalMemoryCapacity.getPropFormat(tag)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'GlobalMemoryCapacity.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(m.getPropFormat(tag)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.getPropFormat(tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(m, tag)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(m, tag) does not work.')
		assert(Format.existsFormat(Element.getPropFormat(m, tag)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropFormat(''GlobalMemoryCapacity'', tag) does not work.')
	end
	 
	% getPropDescription(pointer)
	for prop = 1:1:GlobalMemoryCapacity.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(ischar(GlobalMemoryCapacity.getPropDescription(prop)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'GlobalMemoryCapacity.getPropDescription(prop) does not work.')
		assert(ischar(m.getPropDescription(prop)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.getPropDescription(prop) does not work.')
		assert(ischar(Element.getPropDescription(m, prop)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(m, prop) does not work.')
		assert(ischar(Element.getPropDescription(m, prop)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''GlobalMemoryCapacity'', prop) does not work.')
	 
		assert(ischar(GlobalMemoryCapacity.getPropDescription(tag)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'GlobalMemoryCapacity.getPropDescription(tag) does not work.')
		assert(ischar(m.getPropDescription(tag)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.getPropDescription(tag) does not work.')
		assert(ischar(Element.getPropDescription(m, tag)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(m, tag) does not work.')
		assert(ischar(Element.getPropDescription(m, tag)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.getPropDescription(''GlobalMemoryCapacity'', tag) does not work.')
	end
	 
	% getPropSettings(pointer)
	for prop = 1:1:GlobalMemoryCapacity.getPropNumber()
		tag = m.getPropTag(prop);
	 
		settings = GlobalMemoryCapacity.getPropSettings(prop);
		settings = m.getPropSettings(prop);
		settings = Element.getPropSettings(m, prop);
		settings = Element.getPropSettings('GlobalMemoryCapacity', prop);
	 
		settings = GlobalMemoryCapacity.getPropSettings(tag);
		settings = m.getPropSettings(tag);
		settings = Element.getPropSettings(m, tag);
		settings = Element.getPropSettings('GlobalMemoryCapacity', tag);
	end
	 
	% getPropDefault(pointer)
	for prop = 1:1:GlobalMemoryCapacity.getPropNumber()
		tag = m.getPropTag(prop);
	 
		default = GlobalMemoryCapacity.getPropDefault(prop);
		default = m.getPropDefault(prop);
		default = Element.getPropDefault(m, prop);
		default = Element.getPropDefault('GlobalMemoryCapacity', prop);
	 
		default = GlobalMemoryCapacity.getPropDefault(tag);
		default = m.getPropDefault(tag);
		default = Element.getPropDefault(m, tag);
		default = Element.getPropDefault('GlobalMemoryCapacity', tag);
	end
	 
	% getPropDefaultConditioned(pointer)
	for prop = 1:1:GlobalMemoryCapacity.getPropNumber()
		tag = m.getPropTag(prop);
	 
		conditioned_default = GlobalMemoryCapacity.getPropDefaultConditioned(prop);
		conditioned_default = m.getPropDefaultConditioned(prop);
		conditioned_default = Element.getPropDefaultConditioned(m, prop);
		conditioned_default = Element.getPropDefaultConditioned('GlobalMemoryCapacity', prop);
	 
		conditioned_default = GlobalMemoryCapacity.getPropDefaultConditioned(tag);
		conditioned_default = m.getPropDefaultConditioned(tag);
		conditioned_default = Element.getPropDefaultConditioned(m, tag);
		conditioned_default = Element.getPropDefaultConditioned('GlobalMemoryCapacity', tag);
	end
	 
	% checkProp(pointer, value)
	for prop = 1:1:GlobalMemoryCapacity.getPropNumber()
		tag = m.getPropTag(prop);
	 
		assert(~GlobalMemoryCapacity.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'GlobalMemoryCapacity.checkProp(prop, value) does not work.')
		assert(~m.checkProp(prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.checkProp(prop, value) does not work.')
		assert(~Element.checkProp(m, prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(m, prop, value) does not work.')
		assert(~Element.checkProp('GlobalMemoryCapacity', prop, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''GlobalMemoryCapacity'', prop, value) does not work.')
	 
		assert_with_error('GlobalMemoryCapacity.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.WRONG_INPUT], prop)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.WRONG_INPUT], prop, m)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.WRONG_INPUT], prop, m)
		assert_with_error('Element.checkProp(''GlobalMemoryCapacity'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.WRONG_INPUT], prop)
	 
		assert(~GlobalMemoryCapacity.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'GlobalMemoryCapacity.checkProp(tag, value) does not work.')
		assert(~m.checkProp(tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.checkProp(tag, value) does not work.')
		assert(~Element.checkProp(m, tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(m, tag, value) does not work.')
		assert(~Element.checkProp('GlobalMemoryCapacity', tag, {'probably wrong value', 1}), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''GlobalMemoryCapacity'', tag, value) does not work.')
	 
		assert_with_error('GlobalMemoryCapacity.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.WRONG_INPUT], tag)
		assert_with_error('varargin{2}.checkProp(varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.WRONG_INPUT], tag, m)
		assert_with_error('Element.checkProp(varargin{2}, varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.WRONG_INPUT], tag, m)
		assert_with_error('Element.checkProp(''GlobalMemoryCapacity'', varargin{1}, {''probably wrong value'', 1})', [BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.WRONG_INPUT], tag)
	 
		assert(GlobalMemoryCapacity.checkProp(prop, Element.getPropDefaultConditioned(GlobalMemoryCapacity, prop)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'GlobalMemoryCapacity.checkProp(prop, <conditioned default value>) does not work.')
		assert(m.checkProp(prop, Element.getPropDefaultConditioned(GlobalMemoryCapacity, prop)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.checkProp(prop, <conditioned default value>) does not work.')
		assert(Element.checkProp(m, prop, Element.getPropDefaultConditioned(GlobalMemoryCapacity, prop)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(m, prop, <conditioned default value>) does not work.')
		assert(Element.checkProp('GlobalMemoryCapacity', prop, Element.getPropDefaultConditioned(GlobalMemoryCapacity, prop)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''GlobalMemoryCapacity'', prop, <conditioned default value>) does not work.')
	 
		assert(GlobalMemoryCapacity.checkProp(tag, Element.getPropDefaultConditioned(GlobalMemoryCapacity, prop)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'GlobalMemoryCapacity.checkProp(tag, <conditioned default value>) does not work.')
		assert(m.checkProp(tag, Element.getPropDefaultConditioned(GlobalMemoryCapacity, prop)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'm.checkProp(tag, <conditioned default value>) does not work.')
		assert(Element.checkProp(m, tag, Element.getPropDefaultConditioned(GlobalMemoryCapacity, prop)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(m, tag, <conditioned default value>) does not work.')
		assert(Element.checkProp('GlobalMemoryCapacity', tag, Element.getPropDefaultConditioned(GlobalMemoryCapacity, prop)), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'Element.checkProp(''GlobalMemoryCapacity'', tag, <conditioned default value>) does not work.')
	 
	end
	 
end

%% Test 2: Instantiation - defaults
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = GlobalMemoryCapacity( ...
		GlobalMemoryCapacity.ELCLASS, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.NAME, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.DESCRIPTION, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.TEMPLATE, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.TEMPLATE), ...
		GlobalMemoryCapacity.ID, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.ID), ...
		GlobalMemoryCapacity.LABEL, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.LABEL), ...
		GlobalMemoryCapacity.NOTES, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.NOTES), ...
		GlobalMemoryCapacity.TOSTRING, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.SHAPE, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.SCOPE, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.PARAMETRICITY, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.COMPATIBLE_GRAPHS, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.G, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.G), ...
		GlobalMemoryCapacity.M, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.PFM, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.PFM), ...
		GlobalMemoryCapacity.TRIALS, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.TRIALS), ...
		GlobalMemoryCapacity.TRAINING_SAMPLES, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.TRAINING_SAMPLES), ...
		GlobalMemoryCapacity.TAU_MAX, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.TAU_MAX), ...
		GlobalMemoryCapacity.N_LOWER, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.N_LOWER), ...
		GlobalMemoryCapacity.DENSITY, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.DENSITY) ...
		);
	 
	for prop = 1:1:GlobalMemoryCapacity.getPropNumber()
	 
		% excluded props
		if any(prop == [GlobalMemoryCapacity.PFM])
			continue
		end
	 
		TAG = upper(GlobalMemoryCapacity.getPropTag(prop));
		switch GlobalMemoryCapacity.getPropCategory(prop)
			case {Category.CONSTANT, Category.RESULT, Category.QUERY}
				% getr
				assert( ...
					m.getr(prop) == GlobalMemoryCapacity.getNoValue(), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['Being a ' GlobalMemoryCapacity.getCategoryName(GlobalMemoryCapacity.getPropCategory(prop)) ', GlobalMemoryCapacity.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in GlobalMemoryCapacity.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					m.getr(TAG) == GlobalMemoryCapacity.getNoValue(), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['Being a ' GlobalMemoryCapacity.getCategoryName(GlobalMemoryCapacity.getPropCategory(prop)) ', GlobalMemoryCapacity.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in GlobalMemoryCapacity.getr(' TAG ').'] ...
					)
				% get
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(m.getPropSettings(prop))
					assert( ...
						m.checkFormat(m.getPropFormat(prop), m.get(prop)), ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						['GlobalMemoryCapacity.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						m.checkFormat(m.getPropFormat(prop), m.get(prop), m.getPropSettings(prop)), ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						['GlobalMemoryCapacity.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
			case Category.EVANESCENT
				% getr
				assert( ...
					m.getr(prop) == GlobalMemoryCapacity.getNoValue(), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['Being a ' GlobalMemoryCapacity.getCategoryName(GlobalMemoryCapacity.getPropCategory(prop)) ', GlobalMemoryCapacity.getr(' int2str(prop) ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in GlobalMemoryCapacity.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					m.getr(TAG) == GlobalMemoryCapacity.getNoValue(), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['Being a ' GlobalMemoryCapacity.getCategoryName(GlobalMemoryCapacity.getPropCategory(prop)) ', GlobalMemoryCapacity.getr(' TAG ') must be inizialized to NoValue(). ' ...
					'Or there could be an error in GlobalMemoryCapacity.getr(' TAG ').'] ...
					)
				% get
				warning_backup = warning('off', [BRAPH2.STR ':GlobalMemoryCapacity']);
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				if isempty(m.getPropSettings(prop))
					assert( ...
						m.checkFormat(m.getPropFormat(prop), m.get(prop)), ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						['GlobalMemoryCapacity.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				else
					assert( ...
						m.checkFormat(m.getPropFormat(prop), m.get(prop), m.getPropSettings(prop)), ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						['GlobalMemoryCapacity.get(' int2str(prop) ') returns a value with the wrong format.'] ...
						)
				end
				warning(warning_backup)
			otherwise % case {Category.METADATA, Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isequal(m.getr(prop), GlobalMemoryCapacity.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.getr(' int2str(prop) ') must be inizialized to its default value ' ...
					'given by GlobalMemoryCapacity.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in GlobalMemoryCapacity.getr(' int2str(prop) ').'] ...
					)
				assert( ...
					isequal(m.getr(TAG), GlobalMemoryCapacity.getPropDefaultConditioned(prop)), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.getr(' TAG ') must be inizialized to its default value ' ...
					'given by GlobalMemoryCapacity.getPropDefaultConditioned(' int2str(prop) '). ' ...
					'Or there could be an error in GlobalMemoryCapacity.getr(' TAG ').'] ...
					)
		end
	end
end

%% Test 3: Memorize
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = GlobalMemoryCapacity( ...
		GlobalMemoryCapacity.ELCLASS, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.NAME, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.DESCRIPTION, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.TEMPLATE, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.TEMPLATE), ...
		GlobalMemoryCapacity.ID, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.ID), ...
		GlobalMemoryCapacity.LABEL, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.LABEL), ...
		GlobalMemoryCapacity.NOTES, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.NOTES), ...
		GlobalMemoryCapacity.TOSTRING, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.SHAPE, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.SCOPE, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.PARAMETRICITY, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.COMPATIBLE_GRAPHS, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.G, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.G), ...
		GlobalMemoryCapacity.M, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.PFM, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.PFM), ...
		GlobalMemoryCapacity.TRIALS, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.TRIALS), ...
		GlobalMemoryCapacity.TRAINING_SAMPLES, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.TRAINING_SAMPLES), ...
		GlobalMemoryCapacity.TAU_MAX, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.TAU_MAX), ...
		GlobalMemoryCapacity.N_LOWER, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.N_LOWER), ...
		GlobalMemoryCapacity.DENSITY, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.DENSITY) ...
		);
	 
	for prop = 1:1:GlobalMemoryCapacity.getPropNumber()
	 
		% excluded props
		if any(prop == [GlobalMemoryCapacity.PFM])
			continue
		end
	 
		TAG = upper(GlobalMemoryCapacity.getPropTag(prop));
		switch GlobalMemoryCapacity.getPropCategory(prop)
			case Category.RESULT
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(m.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					m.checkFormat(m.getPropFormat(prop), m.getr(prop),m.getPropSettings(prop)), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
			case Category.QUERY
	% 			warning_backup = warning('off', [BRAPH2.STR ':GlobalMemoryCapacity']);
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
	% following tests excluded because properties QUERY should not be memorized
	% 			warning_backup = warning('off', [BRAPH2.STR ':GlobalMemoryCapacity']);
	% 			assert( ...
	% 				~isa(m.memorize(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
	% 				['GlobalMemoryCapacity.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
	% 				)
	% 			warning(warning_backup)
	% 			assert( ...
	% 				~isa(m.getr(prop), 'NoValue'), ...
	% 				[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
	% 				['GlobalMemoryCapacity.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
	% 				)
	% 			assert( ...
	% 				m.checkFormat(m.getPropFormat(prop), m.getr(prop),m.getPropSettings(prop)), ...
	% 				[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
	% 				['GlobalMemoryCapacity.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
	% 				)
	% 			warning(warning_backup)
			case Category.EVANESCENT
				warning_backup = warning('off', [BRAPH2.STR ':GlobalMemoryCapacity']);
				assert( ...
					~isa(m.get(prop), 'NoValue'), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.get(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				warning(warning_backup)
				assert( ...
					isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.getr(' int2str(prop) ') must be a NoValue, because it should NOT have been memorized.'] ...
					)
				assert( ...
					~isa(m.memorize(prop), 'NoValue'), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.memorize(' int2str(prop) ') must NOT be a NoValue, because it should have been calculated.'] ...
					)
				assert( ...
					~isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.getr(' int2str(prop) ') must NOT be a NoValue, because it should have been memorized.'] ...
					)
				assert( ...
					m.checkFormat(m.getPropFormat(prop), m.getr(prop),m.getPropSettings(prop)), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.getr(' int2str(prop) ') returns a value with the wrong format.'] ...
					)
				if m.getPropFormat(prop) == Format.HANDLE
					warning_backup = warning('off', 'BRAPH2:GlobalMemoryCapacity');
					delete(ancestor(m.get(prop), 'figure'))
					warning(warning_backup)
				end
		end
	end
	 
	if ~isempty(GlobalMemoryCapacity.getProps(Category.RESULT))
		for prop = 1:1:GlobalMemoryCapacity.getPropNumber()
	 
			% excluded props
			if any(prop == [GlobalMemoryCapacity.PFM])
				continue
			end
	 
			switch GlobalMemoryCapacity.getPropCategory(prop)
				case {Category.PARAMETER, Category.DATA}
					assert( ...
						m.isLocked(prop), ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						['GlobalMemoryCapacity.isLocked(' int2str(prop) ') must be locked because a result has been calculated.'] ...
						)
				otherwise
					assert( ...
						~m.isLocked(prop), ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						['GlobalMemoryCapacity.isLocked(' int2str(prop) ') must NOT be locked even though a result has been calculated.'] ...
						)
			end
		end
	end
end

%% Test 4: Lock 1
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = GlobalMemoryCapacity();
	 
	for prop = 1:1:GlobalMemoryCapacity.getPropNumber()
		TAG = upper(GlobalMemoryCapacity.getPropTag(prop));
		assert( ...
			~m.isLocked(prop), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			['GlobalMemoryCapacity.isLocked(' int2str(prop) ') must NOT be locked when it is instantiated.'] ...
			)
		assert( ...
			~m.isLocked(TAG), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			['GlobalMemoryCapacity.isLocked(' TAG ') must NOT be locked when it is instantiated.'] ...
			)
	end
	 
	m.lock()
	 
	for prop = 1:1:GlobalMemoryCapacity.getPropNumber()
		switch GlobalMemoryCapacity.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA}
				assert( ...
					m.isLocked(prop), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.isLocked(' int2str(prop) ') must be locked because the element is now locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT, Category.FIGURE, Category.GUI}
				assert( ...
					~m.isLocked(prop), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.isLocked(' int2str(prop) ') must NOT be locked even though the element is now locked.'] ...
					)
		end
	end
end

%% Test 5: Lock 2
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = GlobalMemoryCapacity();
	 
	warning_backup = warning('off', 'BRAPH2:GlobalMemoryCapacity');
	for prop = 1:1:GlobalMemoryCapacity.getPropNumber()
		m.lock(prop)
		switch GlobalMemoryCapacity.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					m.isLocked(prop), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.isLocked(' int2str(prop) ') must be locked.'] ...
					)
			case {Category.CONSTANT, Category.METADATA, Category.RESULT, Category.QUERY, Category.EVANESCENT}
				assert( ...
					~m.isLocked(prop), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.isLocked(' int2str(prop) ') must NOT be locked even though locking has been attempted.'] ...
					)
		end
	end
	warning(warning_backup)
end

%% Test 6: Check
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = GlobalMemoryCapacity();
	 
	for prop = 1:1:GlobalMemoryCapacity.getPropNumber()
		TAG = upper(GlobalMemoryCapacity.getPropTag(prop));
		assert( ...
			m.isChecked(prop), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			['GlobalMemoryCapacity.isChecked(' int2str(prop) ') must be checked when it is instantiated.'] ...
			)
		assert( ...
			m.isChecked(TAG), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			['GlobalMemoryCapacity.isChecked(' TAG ') must be checked when it is instantiated.'] ...
			)
	end
	 
	m.unchecked()
	 
	for prop = 1:1:GlobalMemoryCapacity.getPropNumber()
		assert( ...
			~m.isChecked(prop), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			['GlobalMemoryCapacity.isChecked(' int2str(prop) ') must NOT be checked because it has been set to unchecked.'] ...
			)
	end
	 
	m.checked()
	 
	for prop = 1:1:GlobalMemoryCapacity.getPropNumber()
		assert( ...
			m.isChecked(prop), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			['GlobalMemoryCapacity.isChecked(' int2str(prop) ') must be checked because it has been set to checked.'] ...
			)
	end
end

%% Test 7: Callbacks
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% basic GlobalMemoryCapacity
	m_0 = GlobalMemoryCapacity( ...
		GlobalMemoryCapacity.ELCLASS, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.NAME, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.DESCRIPTION, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.TEMPLATE, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.TEMPLATE), ...
		GlobalMemoryCapacity.ID, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.ID), ...
		GlobalMemoryCapacity.LABEL, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.LABEL), ...
		GlobalMemoryCapacity.NOTES, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.NOTES), ...
		GlobalMemoryCapacity.TOSTRING, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.SHAPE, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.SCOPE, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.PARAMETRICITY, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.COMPATIBLE_GRAPHS, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.G, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.G), ...
		GlobalMemoryCapacity.M, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.PFM, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.PFM), ...
		GlobalMemoryCapacity.TRIALS, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.TRIALS), ...
		GlobalMemoryCapacity.TRAINING_SAMPLES, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.TRAINING_SAMPLES), ...
		GlobalMemoryCapacity.TAU_MAX, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.TAU_MAX), ...
		GlobalMemoryCapacity.N_LOWER, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.N_LOWER), ...
		GlobalMemoryCapacity.DENSITY, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.DENSITY) ...
		);
	 
	% GlobalMemoryCapacity with 1st callbacks
	m_1 = GlobalMemoryCapacity( ...
		GlobalMemoryCapacity.ELCLASS, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.NAME, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.DESCRIPTION, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.TEMPLATE, m_0.getCallback(4), ..., ...
		GlobalMemoryCapacity.ID, m_0.getCallback(5), ..., ...
		GlobalMemoryCapacity.LABEL, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.LABEL), ...
		GlobalMemoryCapacity.NOTES, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.NOTES), ...
		GlobalMemoryCapacity.TOSTRING, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.SHAPE, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.SCOPE, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.PARAMETRICITY, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.COMPATIBLE_GRAPHS, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.G, m_0.getCallback(13), ..., ...
		GlobalMemoryCapacity.M, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.PFM, m_0.getCallback(15), ..., ...
		GlobalMemoryCapacity.TRIALS, m_0.getCallback(16), ..., ...
		GlobalMemoryCapacity.TRAINING_SAMPLES, m_0.getCallback(17), ..., ...
		GlobalMemoryCapacity.TAU_MAX, m_0.getCallback(18), ..., ...
		GlobalMemoryCapacity.N_LOWER, m_0.getCallback(19), ..., ...
		GlobalMemoryCapacity.DENSITY, m_0.getCallback(20) ... ...
		);
	 
	prop_number = GlobalMemoryCapacity.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(GlobalMemoryCapacity.getPropTag(prop));
		switch GlobalMemoryCapacity.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(m_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(m_1.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(m_1.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% GlobalMemoryCapacity with 2nd callbacks
	m_2 = GlobalMemoryCapacity( ...
		GlobalMemoryCapacity.ELCLASS, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.NAME, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.DESCRIPTION, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.TEMPLATE, m_1.getCallback(4), ..., ...
		GlobalMemoryCapacity.ID, m_1.getCallback(5), ..., ...
		GlobalMemoryCapacity.LABEL, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.LABEL), ...
		GlobalMemoryCapacity.NOTES, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.NOTES), ...
		GlobalMemoryCapacity.TOSTRING, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.SHAPE, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.SCOPE, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.PARAMETRICITY, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.COMPATIBLE_GRAPHS, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.G, m_1.getCallback(13), ..., ...
		GlobalMemoryCapacity.M, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.PFM, m_1.getCallback(15), ..., ...
		GlobalMemoryCapacity.TRIALS, m_1.getCallback(16), ..., ...
		GlobalMemoryCapacity.TRAINING_SAMPLES, m_1.getCallback(17), ..., ...
		GlobalMemoryCapacity.TAU_MAX, m_1.getCallback(18), ..., ...
		GlobalMemoryCapacity.N_LOWER, m_1.getCallback(19), ..., ...
		GlobalMemoryCapacity.DENSITY, m_1.getCallback(20) ... ...
		);
	 
	prop_number = GlobalMemoryCapacity.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(GlobalMemoryCapacity.getPropTag(prop));
		switch GlobalMemoryCapacity.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(m_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(m_2.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(m_2.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
	% GlobalMemoryCapacity with 3rd callbacks
	m_3 = GlobalMemoryCapacity( ...
		GlobalMemoryCapacity.ELCLASS, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.NAME, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.DESCRIPTION, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.TEMPLATE, m_2.getCallback(4), ..., ...
		GlobalMemoryCapacity.ID, m_2.getCallback(5), ..., ...
		GlobalMemoryCapacity.LABEL, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.LABEL), ...
		GlobalMemoryCapacity.NOTES, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.NOTES), ...
		GlobalMemoryCapacity.TOSTRING, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.SHAPE, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.SCOPE, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.PARAMETRICITY, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.COMPATIBLE_GRAPHS, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.G, m_2.getCallback(13), ..., ...
		GlobalMemoryCapacity.M, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.PFM, m_2.getCallback(15), ..., ...
		GlobalMemoryCapacity.TRIALS, m_2.getCallback(16), ..., ...
		GlobalMemoryCapacity.TRAINING_SAMPLES, m_2.getCallback(17), ..., ...
		GlobalMemoryCapacity.TAU_MAX, m_2.getCallback(18), ..., ...
		GlobalMemoryCapacity.N_LOWER, m_2.getCallback(19), ..., ...
		GlobalMemoryCapacity.DENSITY, m_2.getCallback(20) ... ...
		);
	 
	prop_number = GlobalMemoryCapacity.getPropNumber();
	for prop = 1:1:prop_number
		TAG = upper(GlobalMemoryCapacity.getPropTag(prop));
		switch GlobalMemoryCapacity.getPropCategory(prop)
			case {Category.PARAMETER, Category.DATA, Category.FIGURE, Category.GUI}
				assert( ...
					isa(m_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.getr(' int2str(prop) ') must be a callback.'] ...
					)
				assert( ...
					isequal(m_3.get(prop), m_0.get(prop)) && ~isa(m_1.get(prop), 'Callback'), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.get(' int2str(prop) ') must be the actual property and NOT a callback.'] ...
					)
			otherwise
				assert( ...
					~isa(m_3.getr(prop), 'Callback'), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity.getr(' int2str(prop) ') must NOT be a callback.'] ...
					)
		end
	end
	 
end

%% Test 8: Copy
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	% copy empty element
	m = GlobalMemoryCapacity();
	 
	m_copy = m.copy();
	 
	assert(m_copy ~= m, ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'GlobalMemoryCapacity.copy() does not work. A copied element must point to a copied element.')
	assert(isequal(m_copy, m), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'GlobalMemoryCapacity.copy() does not work. A copied element must have the same property values of the original element.')
	 
	for prop = 1:1:GlobalMemoryCapacity.getPropNumber()
		value = m.getr(prop);
		value_copy = m_copy.getr(prop);
		switch GlobalMemoryCapacity.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					'GlobalMemoryCapacity.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'GlobalMemoryCapacity.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'GlobalMemoryCapacity.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'GlobalMemoryCapacity.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
							'GlobalMemoryCapacity.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
							'GlobalMemoryCapacity.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'GlobalMemoryCapacity.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				assert( ...
					m_copy.isLocked(prop) == m.isLocked(prop), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					'GlobalMemoryCapacity.copy() does not work. The locked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					m_copy.isChecked(prop) == m.isChecked(prop), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					'GlobalMemoryCapacity.copy() does not work. The checked status of the copied and original elements must be the same.' ...
					)
				assert( ...
					m_copy.getPropSeed(prop) == m.getPropSeed(prop), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					'GlobalMemoryCapacity.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
					)
		end
	end
	 
	% copy element with default initialization and memorization
	m = GlobalMemoryCapacity( ...
		GlobalMemoryCapacity.ELCLASS, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.NAME, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.DESCRIPTION, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.TEMPLATE, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.TEMPLATE), ...
		GlobalMemoryCapacity.ID, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.ID), ...
		GlobalMemoryCapacity.LABEL, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.LABEL), ...
		GlobalMemoryCapacity.NOTES, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.NOTES), ...
		GlobalMemoryCapacity.TOSTRING, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.SHAPE, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.SCOPE, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.PARAMETRICITY, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.COMPATIBLE_GRAPHS, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.G, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.G), ...
		GlobalMemoryCapacity.M, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.PFM, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.PFM), ...
		GlobalMemoryCapacity.TRIALS, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.TRIALS), ...
		GlobalMemoryCapacity.TRAINING_SAMPLES, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.TRAINING_SAMPLES), ...
		GlobalMemoryCapacity.TAU_MAX, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.TAU_MAX), ...
		GlobalMemoryCapacity.N_LOWER, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.N_LOWER), ...
		GlobalMemoryCapacity.DENSITY, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.DENSITY) ...
		);
	 
	for prop = 1:1:GlobalMemoryCapacity.getPropNumber()
		if GlobalMemoryCapacity.getPropCategory(prop) == Category.QUERY
			% properties QUERY should not be memorized
			% warning_backup = warning('off', [BRAPH2.STR ':GlobalMemoryCapacity']);
			% m.memorize(prop);
			% warning(warning_backup)
		elseif GlobalMemoryCapacity.getPropCategory(prop) == Category.EVANESCENT && m.getPropFormat(prop) == Format.HANDLE
			m.memorize(prop);
			warning_backup = warning('off', 'BRAPH2:GlobalMemoryCapacity');
			delete(ancestor(m.get(prop), 'figure'))
			warning(warning_backup)
		else
			m.memorize(prop);
		end
	end
	 
	% copy element with default initialization
	m_copy = m.copy();
	 
	for prop = 1:1:GlobalMemoryCapacity.getPropNumber()
		value = m.getr(prop);
		value_copy = m_copy.getr(prop);
		switch GlobalMemoryCapacity.getPropCategory(prop)
			case {Category.EVANESCENT Category.QUERY}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					'GlobalMemoryCapacity.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'GlobalMemoryCapacity.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'GlobalMemoryCapacity.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'GlobalMemoryCapacity.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
							'GlobalMemoryCapacity.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
							'GlobalMemoryCapacity.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'GlobalMemoryCapacity.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
	 
					assert( ...
						m_copy.isLocked(prop) == m.isLocked(prop), ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'GlobalMemoryCapacity.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						m_copy.isChecked(prop) == m.isChecked(prop), ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'GlobalMemoryCapacity.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						m_copy.getPropSeed(prop) == m.getPropSeed(prop), ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'GlobalMemoryCapacity.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
	% copy element with callbacks
	m_0 = GlobalMemoryCapacity( ...
		GlobalMemoryCapacity.ELCLASS, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.NAME, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.DESCRIPTION, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.TEMPLATE, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.TEMPLATE), ...
		GlobalMemoryCapacity.ID, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.ID), ...
		GlobalMemoryCapacity.LABEL, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.LABEL), ...
		GlobalMemoryCapacity.NOTES, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.NOTES), ...
		GlobalMemoryCapacity.TOSTRING, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.SHAPE, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.SCOPE, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.PARAMETRICITY, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.COMPATIBLE_GRAPHS, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.G, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.G), ...
		GlobalMemoryCapacity.M, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.PFM, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.PFM), ...
		GlobalMemoryCapacity.TRIALS, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.TRIALS), ...
		GlobalMemoryCapacity.TRAINING_SAMPLES, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.TRAINING_SAMPLES), ...
		GlobalMemoryCapacity.TAU_MAX, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.TAU_MAX), ...
		GlobalMemoryCapacity.N_LOWER, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.N_LOWER), ...
		GlobalMemoryCapacity.DENSITY, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.DENSITY) ...
		);
	 
	m = GlobalMemoryCapacity( ...
		GlobalMemoryCapacity.ELCLASS, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.NAME, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.DESCRIPTION, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.TEMPLATE, m_0.getCallback(4), ..., ...
		GlobalMemoryCapacity.ID, m_0.getCallback(5), ..., ...
		GlobalMemoryCapacity.LABEL, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.LABEL), ...
		GlobalMemoryCapacity.NOTES, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.NOTES), ...
		GlobalMemoryCapacity.TOSTRING, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.SHAPE, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.SCOPE, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.PARAMETRICITY, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.COMPATIBLE_GRAPHS, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.G, m_0.getCallback(13), ..., ...
		GlobalMemoryCapacity.M, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.PFM, m_0.getCallback(15), ..., ...
		GlobalMemoryCapacity.TRIALS, m_0.getCallback(16), ..., ...
		GlobalMemoryCapacity.TRAINING_SAMPLES, m_0.getCallback(17), ..., ...
		GlobalMemoryCapacity.TAU_MAX, m_0.getCallback(18), ..., ...
		GlobalMemoryCapacity.N_LOWER, m_0.getCallback(19), ..., ...
		GlobalMemoryCapacity.DENSITY, m_0.getCallback(20) ... ...
		);
	 
	m_copy = m.copy();
	m_0_copy = m_copy.getr('ID').get('EL');
	 
	for prop = 1:1:GlobalMemoryCapacity.getPropNumber()
		value = m.getr(prop);
		value_copy = m_copy.getr(prop);
		switch GlobalMemoryCapacity.getPropCategory(prop)
			case {Category.EVANESCENT}
				assert( ...
					isa(value_copy, 'NoValue'), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					'GlobalMemoryCapacity.copy() does not work. The copied value of an EVANESCENT property must be NoValue.' ...
					)
			otherwise
				if isa(value, 'NoValue')
					assert( ...
						value_copy == value, ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'GlobalMemoryCapacity.copy() does not work. There should be a unique instance of NoValue.' ...
						)
				elseif isa(value, 'Element')
					assert( ...
						value_copy ~= value, ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'GlobalMemoryCapacity.copy() does not work. The handle of a copied element should point to a copied element.' ...
						)
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'GlobalMemoryCapacity.copy() does not work. When empty, a copied element should be equal to the element.' ...
						)
				elseif iscell(value) && all(all(cellfun(@(x) isa(x, 'Element'), value)))
					for j = 1:1:length(value)
						assert( ...
							value_copy ~= value, ...
							[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
							'GlobalMemoryCapacity.copy() does not work. The handle of a copied element should point to a copied element.' ...
							)
						assert( ...
							isequal(value_copy, value), ...
							[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
							'GlobalMemoryCapacity.copy() does not work. When empty, a copied element should be equal to the element.' ...
							)
					end
				else
					assert( ...
						isequal(value_copy, value), ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'GlobalMemoryCapacity.copy() does not work. The value copy should be equal to the original.' ...
						)
				end
				if isa(value, 'Callback')
					assert( ...
						value == m_0.getCallback(prop), ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'GlobalMemoryCapacity.copy() does not work. The callback should be obtained from GlobalMemoryCapacity.getCallback().' ...
						)
					assert( ...
						value_copy == m_0_copy.getCallback(prop), ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'GlobalMemoryCapacity.copy() does not work. The callback should be obtained from GlobalMemoryCapacity.getCallback().' ...
						)
				end
	 
					assert( ...
						m_copy.isLocked(prop) == m.isLocked(prop), ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'GlobalMemoryCapacity.copy() does not work. The locked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						m_copy.isChecked(prop) == m.isChecked(prop), ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'GlobalMemoryCapacity.copy() does not work. The checked status of the copied and original elements must be the same.' ...
						)
	 
					assert( ...
						m_copy.getPropSeed(prop) == m.getPropSeed(prop), ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'GlobalMemoryCapacity.copy() does not work. The randomization seeds of the copied and original elements must be the same.' ...
						)
		end
	end
	 
end

%% Test 9: Template
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m_template = GlobalMemoryCapacity();
	m = GlobalMemoryCapacity('TEMPLATE', m_template);
	 
	for prop = 1:1:GlobalMemoryCapacity.getPropNumber()
	 
		% excluded props
		if any(prop == [GlobalMemoryCapacity.PFM])
			continue
		end
	 
		TAG = upper(GlobalMemoryCapacity.getPropTag(prop));
		switch GlobalMemoryCapacity.getPropCategory(prop)
			case {Category.PARAMETER}
				if prop == GlobalMemoryCapacity.TEMPLATE
					assert( ...
						isa(m.getr(prop), 'GlobalMemoryCapacity'), ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'GlobalMemoryCapacity TEMPLATE does not work. GlobalMemoryCapacity.getr(''TEMPLATE'') should be a GlobalMemoryCapacity element.' ...
						)
					assert( ...
						isa(m_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						'GlobalMemoryCapacity TEMPLATE does not work. GlobalMemoryCapacity_template.getr(''TEMPLATE'') should be a NoValue.' ...
						)
				else
					assert( ...
						isa(m.getr(prop), 'Callback'), ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						['GlobalMemoryCapacity TEMPLATE does not work. GlobalMemoryCapacity.getr(' TAG ') should be a Callback.'] ...
						)
					assert( ...
						m.getr(prop).get('EL') == m_template && m.getr(prop).get('PROP') == prop && strcmp(m.getr(prop).get('TAG'), TAG), ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						['GlobalMemoryCapacity TEMPLATE does not work. GlobalMemoryCapacity.getr(' TAG ') should be a Callback to m_template.' TAG '.'] ...
						)
					assert( ...
						isa(m_template.getr(prop), 'NoValue'), ...
						[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
						['GlobalMemoryCapacity TEMPLATE does not work. GlobalMemoryCapacity_template.getr(' TAG ') should be a NoValue.'] ...
						)
				end
			otherwise
				assert( ...
					isa(m.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity TEMPLATE does not work. GlobalMemoryCapacity.getr(' TAG ') should be a NoValue.'] ...
					)
				assert( ...
					isa(m_template.getr(prop), 'NoValue'), ...
					[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
					['GlobalMemoryCapacity TEMPLATE does not work. GlobalMemoryCapacity_template.getr(' TAG ') should be a NoValue.'] ...
					)
		end
	end
end

%% Test 10: Save Load
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = GlobalMemoryCapacity( ...
		GlobalMemoryCapacity.ELCLASS, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.NAME, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.DESCRIPTION, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.TEMPLATE, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.TEMPLATE), ...
		GlobalMemoryCapacity.ID, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.ID), ...
		GlobalMemoryCapacity.LABEL, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.LABEL), ...
		GlobalMemoryCapacity.NOTES, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.NOTES), ...
		GlobalMemoryCapacity.TOSTRING, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.SHAPE, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.SCOPE, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.PARAMETRICITY, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.COMPATIBLE_GRAPHS, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.G, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.G), ...
		GlobalMemoryCapacity.M, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.PFM, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.PFM), ...
		GlobalMemoryCapacity.TRIALS, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.TRIALS), ...
		GlobalMemoryCapacity.TRAINING_SAMPLES, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.TRAINING_SAMPLES), ...
		GlobalMemoryCapacity.TAU_MAX, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.TAU_MAX), ...
		GlobalMemoryCapacity.N_LOWER, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.N_LOWER), ...
		GlobalMemoryCapacity.DENSITY, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.DENSITY) ...
		);
	 
	filename = [fileparts(which('test_braph2')) filesep 'globalmemorycapacity_to_be_erased.b2'];
	 
	Element.save(m, filename)
	 
	m_loaded = Element.load(filename);
	 
	assert( ...
		isequal(m.copy(), m_loaded), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'GlobalMemoryCapacity.save(m) and/or GlobalMemoryCapacity.load() do not work.' ...
		)
	 
	delete(filename)
end

%% Test 11: JSON
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	m = GlobalMemoryCapacity( ...
		GlobalMemoryCapacity.ELCLASS, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.NAME, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.DESCRIPTION, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.TEMPLATE, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.TEMPLATE), ...
		GlobalMemoryCapacity.ID, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.ID), ...
		GlobalMemoryCapacity.LABEL, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.LABEL), ...
		GlobalMemoryCapacity.NOTES, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.NOTES), ...
		GlobalMemoryCapacity.TOSTRING, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.SHAPE, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.SCOPE, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.PARAMETRICITY, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.COMPATIBLE_GRAPHS, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.G, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.G), ...
		GlobalMemoryCapacity.M, GlobalMemoryCapacity.getNoValue(), ...
		GlobalMemoryCapacity.PFM, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.PFM), ...
		GlobalMemoryCapacity.TRIALS, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.TRIALS), ...
		GlobalMemoryCapacity.TRAINING_SAMPLES, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.TRAINING_SAMPLES), ...
		GlobalMemoryCapacity.TAU_MAX, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.TAU_MAX), ...
		GlobalMemoryCapacity.N_LOWER, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.N_LOWER), ...
		GlobalMemoryCapacity.DENSITY, GlobalMemoryCapacity.getPropDefault(GlobalMemoryCapacity.DENSITY) ...
		);
	 
	[json, struct, el_list] = encodeJSON(m);
	[m_dec, struct_dec, el_list_dec] = Element.decodeJSON(json);
	 
	assert(m_dec ~= m, ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		'GlobalMemoryCapacity.encodeJSON() or GlobalMemoryCapacity.decodeJSON() does not work. A JSON encoded/decoded element must point to an element other than the original one.' ...
		)
	if all(cellfun(@(prop) GlobalMemoryCapacity.getPropFormat(prop), num2cell(GlobalMemoryCapacity.getProps())) == Format.HANDLE) && all(cellfun(@(prop) GlobalMemoryCapacity.getPropFormat(prop), num2cell(GlobalMemoryCapacity.getProps())) == Format.NET)
		assert(isequal(m_dec, m), ...
			[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
			'GlobalMemoryCapacity.encodeJSON() or GlobalMemoryCapacity.decodeJSON() does not work. A JSON encoded/decoded element must have the same property values of the original element.' ...
			)
	end
end

%% Test 12: example test
if rand() >= (1 - .01) * BRAPH2TEST.RANDOM
	test_MC('global')
end

%% Test 13: No Figures Left
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	assert(isempty(findall(0, 'type', 'figure')), ...
		[BRAPH2.STR ':GlobalMemoryCapacity:' BRAPH2.FAIL_TEST], ...
		[' When testing GlobalMemoryCapacity no figures should be left over, either visible or not. ' ...
		int2str(length(findall(0, 'type', 'figure'))) ' figure(s) were left over.'] ...
		)
end

%% Test 14: Delete Figures
if rand() >= (1 - 1) * BRAPH2TEST.RANDOM
	delete(findall(0, 'type', 'figure'))
end

